const CHANGE_CITY = `CHANGE_CITY`;
const GET_PLACES = `GET_PLACES`;
const SET_ACTIVE_PLACE = `SET_ACTIVE_PLACE`;
const SORT_PLACES = `SORT_PLACES`;

export {
  CHANGE_CITY,
  GET_PLACES,
  SET_ACTIVE_PLACE,
  SORT_PLACES
};
