const NameSpace = {
  ACTIVE_OFFER: `ACTIVE_OFFER`,
  CITIES: `CITIES`,
  CURRENT_CITY: `CURRENT_CITY`,
  OFFERS: `OFFERS`,
  OFFERS_NEARBY: `OFFERS_NEARBY`,
  SORTING_OPTION: `SORTING_OPTION`,
  AUTH_STATUS: `AUTH_STATUS`,
  USER: `USER`,
  COMMENTS: `COMMENTS`,
  SENDING_COMMENT: `SENDING_COMMENT`,
  COMMENT_ERROR: `COMMENT_ERROR`
};

export default NameSpace;
