const NameSpace = {
  ACTIVE_OFFER: `ACTIVE_OFFER`,
  CITIES: `CITIES`,
  CURRENT_CITY: `CURRENT_CITY`,
  OFFERS: `OFFERS`,
  SORTING_OPTION: `SORTING_OPTION`,
  AUTH_STATUS: `AUTH_STATUS`
};

export default NameSpace;
