const SET_CURRENT_CITY = `SET_CURRENT_CITY`;
const SET_ACTIVE_OFFER = `SET_ACTIVE_OFFER`;
const SET_SORTING_OPTION = `SET_SORTING_OPTION`;
const LOAD_OFFERS = `LOAD_OFFERS`;
const REQUIRE_AUTHORIZATION = `REQUIRE_AUTHORIZATION`;
const SET_USER = `SET_USER`;
const LOAD_OFFERS_NEARBY = `LOAD_OFFERS_NEARBY`;
const LOAD_COMMENTS = `LOAD_COMMENTS`;
const SET_SENDING_COMMENT = `SET_SENDING_COMMENT`;
const SET_COMMENT_ERROR = `SET_COMMENT_ERROR`;
const REPLACE_OFFER = `PEPLACE_OFFER`;
const LOAD_FAVORITE_OFFERS = `LOAD-FAVORITE-OFFERS`;

export {
  SET_CURRENT_CITY,
  SET_ACTIVE_OFFER,
  SET_SORTING_OPTION,
  LOAD_OFFERS,
  REQUIRE_AUTHORIZATION,
  SET_USER,
  LOAD_OFFERS_NEARBY,
  LOAD_COMMENTS,
  SET_SENDING_COMMENT,
  SET_COMMENT_ERROR,
  REPLACE_OFFER,
  LOAD_FAVORITE_OFFERS
};
