const SET_CURRENT_CITY = `SET_CURRENT_CITY`;
const SET_ACTIVE_OFFER = `SET_ACTIVE_OFFER`;
const SET_SORTING_OPTION = `SET_SORTING_OPTION`;
const LOAD_OFFERS = `LOAD_OFFERS`;
const REQUIRE_AUTHORIZATION = `REQUIRE_AUTHORIZATION`;

export {
  SET_CURRENT_CITY,
  SET_ACTIVE_OFFER,
  SET_SORTING_OPTION,
  LOAD_OFFERS,
  REQUIRE_AUTHORIZATION
};
